In [1]:
%%capture
# Installs Unsloth, Xformers (Flash Attention) and all other packages!
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"

# We have to check which Torch version for Xformers (2.3 -> 0.0.27)
from torch import __version__; from packaging.version import Version as V
xformers = "xformers==0.0.27" if V(__version__) < V("2.4.0") else "xformers"
!pip install --no-deps {xformers} trl peft accelerate bitsandbytes triton
!pip install Pillow

!pip install sentence_transformers

In [2]:
import requests
import json
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.font_manager as fm
import matplotlib.image as mpimg
from io import StringIO, BytesIO
import PIL


# url = 'manual_add.json'
# response = requests.get(url)


# logo_banner = 'horizontal-logo.png'
# logo_response = requests.get(logo_banner)
logo_img = mpimg.imread('horizontal-logo.png')



import json
with open('final_file.json', 'r') as json_file:
    data = json.load(json_file)

# Load the CSV string into a pandas DataFrame
df = pd.read_csv('Joined_DF_0.csv')
df['action_time'] = pd.to_datetime(df['action_time'],format='ISO8601')
df['Date']=pd.to_datetime(df['Date'])
manjari_bold_path = 'Manjari-Bold.ttf'
manjari_regular_path = 'Manjari-Regular.ttf'
manjari_thin_path = 'Manjari-thin.ttf'

dark = "#3B3365"
medium = "#8F81DD"
light = "#BCADFF"
peach = "#FFEEDD"

# Load the custom font
manjari_bold = fm.FontProperties(fname=manjari_bold_path)
manjari_regular = fm.FontProperties(fname=manjari_regular_path)
manjari_thin = fm.FontProperties(fname=manjari_thin_path)
df

,staff,replaced,Date,action_time,product,type,quantity,base,total
0,Amanda,NaN,2024-06-17,2024-06-17 10:10:30,Blue Machine,Photo,1.0,10.0,10.0
1,Amanda,NaN,2024-06-17,2024-06-17 10:13:38,Blue Machine,Photo,1.0,10.0,10.0
2,Amanda,NaN,2024-06-17,2024-06-17 10:24:14,Purple Machine,Photo,1.0,10.0,0.0
3,Amanda,NaN,2024-06-17,2024-06-17 11:56:39,Purple Machine,Photo,1.0,10.0,10.0
4,Amanda,NaN,2024-06-17,2024-06-17 12:28:02,Purple Machine,Photo,1.0,10.0,10.0
...,...,...,...,...,...,...,...,...,...
2505,Nicole,Jess,2024-08-22,2024-08-22 17:12:08,Purple Machine,Copy/Print,2.0,5.0,10.0
2506,Nicole,Jess,2024-08-22,2024-08-22 17:16:03,Blue Machine,Photo,1.0,10.0,10.0
2507,Nicole,Jess,2024-08-22,2024-08-22 17:21:34,Blue Machine,Copy/Print,2.0,5.0,10.0
2508,Nicole,Jess,2024-08-22,2024-08-22 17:26:11,Blue Machine,Photo,1.0,10.0,0.0
2509,Nicole,Jess,2024-08-22,2024-08-22 17:30:34,Blue Machine,Copy/Print,2.0,5.0,10.0

In [3]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 2048 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

# 4bit pre quantized models we support for 4x faster downloading + no OOMs.
fourbit_models = [
    "unsloth/Meta-Llama-3.1-8B-bnb-4bit",      # Llama-3.1 15 trillion tokens model 2x faster!
    "unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit",
    "unsloth/Meta-Llama-3.1-70B-bnb-4bit",
    "unsloth/Meta-Llama-3.1-405B-bnb-4bit",    # We also uploaded 4bit for 405b!
    "unsloth/Mistral-Nemo-Base-2407-bnb-4bit", # New Mistral 12b 2x faster!
    "unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit",
    "unsloth/mistral-7b-v0.3-bnb-4bit",        # Mistral v3 2x faster!
    "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",
    "unsloth/Phi-3.5-mini-instruct",           # Phi-3.5 2x faster!
    "unsloth/Phi-3-medium-4k-instruct",
    "unsloth/gemma-2-9b-bnb-4bit",
    "unsloth/gemma-2-27b-bnb-4bit",            # Gemma 2x faster!
] # More models at https://huggingface.co/unsloth

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Meta-Llama-3.1-8B",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    # token = "hf_...", # use one if using gated models like meta-llama/Llama-2-7b-hf
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
==((====))==  Unsloth 2024.9.post4: Fast Llama patching. Transformers = 4.44.2.
   \\   /|    GPU: Tesla T4. Max memory: 14.748 GB. Platform = Linux.
O^O/ \_/ \    Pytorch: 2.4.1+cu121. CUDA = 7.5. CUDA Toolkit = 12.1.
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.28.post1. FA2 = False]
 "-____-"     Free Apache license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/5.70G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/230 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/50.6k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/345 [00:00<?, ?B/s]

In [4]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
)

Unsloth 2024.9.post4 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

In [5]:
alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{}

### Input:
{}

### Response:
{}"""

EOS_TOKEN = tokenizer.eos_token # Must add EOS_TOKEN
def formatting_prompts_func(examples):
    instructions = examples["instruction"]
    inputs       = examples["input"]
    outputs      = examples["output"]
    texts = []
    for instruction, input, output in zip(instructions, inputs, outputs):
        # Must add EOS_TOKEN, otherwise your generation will go on forever!
        text = alpaca_prompt.format(instruction, input, output) + EOS_TOKEN
        texts.append(text)
    return { "text" : texts, }
pass

from datasets import load_dataset, Dataset
dataset = Dataset.from_dict({
    'instruction': [entry['instruction'] for entry in data],
    'input': [''] * len(data),
    'output': [entry['output'] for entry in data]
}, split="train")
dataset = dataset.map(formatting_prompts_func, batched = True,)

Map:   0%|          | 0/68 [00:00<?, ? examples/s]

In [6]:
from trl import SFTTrainer
from transformers import TrainingArguments
from unsloth import is_bfloat16_supported

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False, # Can make training 5x faster for short sequences.
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 20,
        learning_rate = 2e-4,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
    ),
)

Map (num_proc=2):   0%|          | 0/68 [00:00<?, ? examples/s]

max_steps is given, it will override any value given in num_train_epochs

In [7]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs = 1
   \\   /|    Num examples = 68 | Num Epochs = 3
O^O/ \_/ \    Batch size per device = 2 | Gradient Accumulation steps = 4
\        /    Total batch size = 8 | Total steps = 20
 "-____-"     Number of trainable parameters = 41,943,040

In [8]:
with open('Joined_DF_0.csv', mode='r', newline='', encoding='utf-8') as csvfile:
    csvreader = csv.reader(csvfile, quotechar='"', delimiter=',')
    headers = next(csvreader)
    combined_data = ['"' + '","'.join(headers) + '"']

    for row in csvreader:
        combined_row = '"' + '","'.join(row) + '"'  # Add quotes around each cell
        combined_data.append(combined_row)

# Join all rows into a single string separated by newlines
training_input = '\n'.join(combined_data)
training_input

'"staff","replaced","Date","action_time","product","type","quantity","base","total"\n"Amanda","","2024-06-17","2024-06-17 10:10:30","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 10:13:38","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 10:24:14","Purple Machine","Photo","1.0","10.0","0.0"\n"Amanda","","2024-06-17","2024-06-17 11:56:39","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 12:28:02","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 12:49:20","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 12:52:49","Blue Machine","Photo","1.0","10.0","0.0"\n"Amanda","","2024-06-17","2024-06-17 13:03:23","Purple Machine","Photo","1.0","10.0","0.0"\n"Amanda","","2024-06-17","2024-06-17 14:23:21","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 14:27:40","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-17","2024-06-17 14:30:42","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 14:36:49","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 14:42:54","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 14:45:05","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 14:58:51","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 15:03:07","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-17","2024-06-17 15:06:18","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 15:07:49","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 15:12:00","Blue Machine","Copy/Print","2.0","5.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 15:23:03","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 15:32:24","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 15:37:47","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 15:44:28","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 15:47:43","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 16:06:19","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 16:14:54","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 16:18:12","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 16:21:49","Blue Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-17","2024-06-17 16:25:06","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 16:27:15","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 16:27:41","Blue Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-17","2024-06-17 16:49:03.141000","BTS Map of the Soul: Persona (Random Ver.)","BTS","1.0","35.95","35.95"\n"Amanda","","2024-06-17","2024-06-17 16:49:53","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-17","2024-06-17 16:53:58","Purple Machine","Photo","1.0","10.0","0.0"\n"Amanda","","2024-06-22","2024-06-22 10:32:37","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 10:36:22","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 10:37:16","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-22","2024-06-22 10:45:15","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 10:58:13.649000","","Unknown","1.0","5.0","5.0"\n"Amanda","","2024-06-22","2024-06-22 11:26:26.921000","Enhypen Orange Blood (Random Ver.)","ENHYPEN","1.0","39.95","39.95"\n"Amanda","","2024-06-22","2024-06-22 11:33:51","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 11:40:22","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 12:13:33","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 12:20:03","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 12:21:35.716000","BTS JungKook Golden (Random Ver.)","BTS JungKook","1.0","39.95","39.95"\n"Amanda","","2024-06-22","2024-06-22 12:28:11","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 12:34:10","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 12:40:37","Blue Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-22","2024-06-22 12:43:18.332000","Enhypen Orange Blood (Random Ver.)","ENHYPEN","1.0","39.95","39.95"\n"Amanda","","2024-06-22","2024-06-22 12:47:22","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 12:47:30","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 12:50:46","Blue Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-22","2024-06-22 12:52:59","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 12:53:41","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-22","2024-06-22 12:55:56","Blue Machine","Copy/Print","2.0","5.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 12:59:00","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 13:01:41","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 13:07:00","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 13:09:46","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 13:24:11","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 13:25:07","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 13:29:47","Blue Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-22","2024-06-22 13:32:26","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 13:37:55","Blue Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-22","2024-06-22 13:40:26","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 13:42:46","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 13:49:23","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 13:52:40","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 14:02:44","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 14:09:22.773000","I’VE Mine (Random Ver.)","Miscellaneous","1.0","36.95","36.95"\n"Amanda","","2024-06-22","2024-06-22 14:25:51","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 14:32:46","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 14:33:42","Purple Machine","Photo","1.0","10.0","0.0"\n"Amanda","","2024-06-22","2024-06-22 14:36:46","Blue Machine","Copy/Print","3.0","5.0","15.0"\n"Amanda","","2024-06-22","2024-06-22 14:43:18","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 14:47:27.366000","Stray Kids Rock-Star (Rock, Roll Ver.) ","Stray Kids","1.0","32.95","32.95"\n"Amanda","","2024-06-22","2024-06-22 14:52:51","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 15:00:11","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 15:12:43","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 15:25:23","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 15:46:51","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 15:49:57","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-22","2024-06-22 15:52:56","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 15:53:35","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 16:04:34","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 16:15:32","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 16:36:54","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-22","2024-06-22 16:41:20","Purple Machine","Copy/Print","5.0","5.0","25.0"\n"Amanda","","2024-06-22","2024-06-22 16:53:47","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","","","","","",""\n"Amanda","","2024-06-24","2024-06-24 11:46:55","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 12:07:34","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 12:08:13","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 12:13:12","Purple Machine","Copy/Print","3.0","5.0","15.0"\n"Amanda","","2024-06-24","2024-06-24 12:50:28","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 13:00:17","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 13:00:40","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 13:05:25","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-24","2024-06-24 13:10:59","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 13:17:14","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 13:19:05","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-24","2024-06-24 13:20:59","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 13:30:30","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 13:46:50","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 13:56:24","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 14:20:47","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 14:23:10","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-24","2024-06-24 14:26:34","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 14:29:59","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-24","2024-06-24 14:31:36","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 14:48:43","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 15:47:35","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 15:55:40","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 16:04:34","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 16:34:11","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-24","2024-06-24 16:38:58","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-24","2024-06-24 16:47:05","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 10:04:07","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 10:08:59","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 10:25:11","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 10:36:07","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 10:43:19","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 12:01:02","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 12:01:24","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 12:08:23","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 12:15:01","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 12:18:57.233000","","Unknown","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 12:22:41.399000","","Unknown","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 12:27:17","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 12:35:30","Purple Machine","Photo","1.0","10.0","0.0"\n"Amanda","","2024-06-29","2024-06-29 12:38:27","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-29","2024-06-29 12:38:29","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 12:43:34","Blue Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-29","2024-06-29 12:45:03","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 12:50:06","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 13:15:39","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 13:21:40","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 13:25:47","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 13:28:04","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 13:32:57","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 13:35:23","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 13:41:31.731000","Ateez The World EP.FIN : Will (Random Ver.)","ATEEZ","1.0","31.95","31.95"\n"Amanda","","2024-06-29","2024-06-29 13:44:27","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 13:45:50.753000","Seventeen - Seventeenth Heaven (Carat Ver.)","Seventeen","1.0","34.95","34.95"\n"Amanda","","2024-06-29","2024-06-29 13:48:56","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-29","2024-06-29 13:57:53","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 14:04:45","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 14:11:59","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 14:39:56","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 14:40:57","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 14:45:48","Blue Machine","Copy/Print","2.0","5.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 14:50:06","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 14:53:54","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 15:02:04","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 15:04:52","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 15:11:13","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 15:20:16","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 15:30:18","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 15:30:40","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 15:37:08","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 15:38:03","Blue Machine","Photo","1.0","0.0","0.0"\n"Amanda","","2024-06-29","2024-06-29 15:46:30","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 16:14:20","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 16:17:04","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-29","2024-06-29 16:27:16","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 16:34:00","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 16:40:37","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 16:41:22","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 16:47:43","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-06-29","2024-06-29 16:52:40","Blue Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-06-29","2024-06-29 16:59:33","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","","","","","",""\n"Amanda","","2024-07-06","2024-07-06 10:56:05","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 11:08:49","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 11:23:11","Blue Machine","Photo","1.0","10.0","0.0"\n"Amanda","","2024-07-06","2024-07-06 11:28:39","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 11:41:18","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 11:47:13","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-07-06","2024-07-06 11:52:21","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 11:59:30","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 12:30:08","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 12:33:32","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-07-06","2024-07-06 12:51:12","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 12:57:15","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-07-06","2024-07-06 12:59:46","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 13:03:47","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 13:03:48","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 13:10:28","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-07-06","2024-07-06 13:17:49","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 13:21:09","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-07-06","2024-07-06 13:24:02","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 13:27:40","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-07-06","2024-07-06 13:28:38","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 13:32:34","Blue Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-07-06","2024-07-06 14:00:42","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 14:01:08","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 14:06:31","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 14:44:50","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 14:44:58","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 14:49:23","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-07-06","2024-07-06 14:54:27","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 14:58:30","Purple Machine","Copy/Print","1.0","5.0","5.0"\n"Amanda","","2024-07-06","2024-07-06 15:07:24","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 15:23:25","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 15:23:27","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 15:30:19","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 15:37:46","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 15:38:29","Purple Machine","Photo","1.0","10.0","0.0"\n"Amanda","","2024-07-06","2024-07-06 15:46:33","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 15:47:52","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 15:52:56","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 15:56:41","Blue Machine","Photo","1.0","10.0","10.0"\n"Amanda","","2024-07-06","2024-07-06 15:59:33","Purple Machine","Photo","1.0","10.0","10.0"\n"Amanda","",

In [9]:
test_prompts = ["give me a table of total sales grouped by staff - order it by sales",
                "how many photos were sold in august",
                "Can you produce a graph on who worked the most shifts?",
                "How many BTS albums sold in July?"
                "How many copies were sold over time?"]

In [18]:
#inference
FastLanguageModel.for_inference(model) # Enable native 2x faster inference
model.to('cuda')
from transformers import TextStreamer
all_outputs = []

torch.cuda.empty_cache()

for prompt in test_prompts:

  inputs = tokenizer(
  [
      alpaca_prompt.format(
          prompt, # instruction
          training_input, #file content
          "", # output - leave this blank for generation!
      )
  ], return_tensors = "pt").to("cuda")
  output = model.generate(**inputs, max_new_tokens = 512)
  output_text = tokenizer.decode(output[0], skip_special_tokens=True)
  all_outputs.append(output_text)

OutOfMemoryError: CUDA out of memory. Tried to allocate 816.00 MiB. GPU 0 has a total capacity of 14.75 GiB of which 475.06 MiB is free. Process 4244 has 14.28 GiB memory in use. Of the allocated memory 14.10 GiB is allocated by PyTorch, and 28.58 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [ ]:
import re
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')
# check multiple models




def scoring_syntax(output):
  try:
    exec(output)
    print("Success")
    return 1
  except Exception as error:
    print("Fail")
    print(f"Failed exception: {error}")
    return 0


def scoring_title(query,output):
  title = re.findall(r'\.set_title\((["\'])(.*?)\1\)', output)
  if len(title)==0:
    print('No Title found!')
    return 0
  query_embedding = model.encode(query, convert_to_tensor=True)
  title_embedding = model.encode(title, convert_to_tensor=True)

  # Compute cosine similarity
  similarity = util.cos_sim(query_embedding, title_embedding)
  return similarity.item()

syntax_score = 0
title_score = 0
for output_text in all_outputs:
  trimmed = re.search(r'### Response\s*(.*)', output_text, re.DOTALL)
  final = trimmed.group(1).strip()
  query = re.search(r'### Instruction:\s*(.*?)\s*### Input:', output_text, re.DOTALL).group(1).strip()
  s_score = scoring_syntax(final)
  t_score = scoring_title(query,final)
  # print(f'Score on the Syntax: {s_score}')
  # print(f'Score on the Title: {t_score}')
  syntax_score += s_score
  title_score += t_score

print(f"Final Score on the Syntax: {syntax_score}")
print(f"Final Score on the Title: {title_score}")

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.78k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/686 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/328M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.12k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Fail
Failed exception: invalid syntax (<string>, line 1)
Score on the Syntax: 0
No Title found!
Score on the Title: 0

In [ ]:
#saving
model.save_pretrained("llama") # Local saving
tokenizer.save_pretrained("llama")

In [ ]:
#load:
if True:
    from unsloth import FastLanguageModel
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = "lora_model", # YOUR MODEL YOU USED FOR TRAINING
        max_seq_length = max_seq_length,
        dtype = dtype,
        load_in_4bit = load_in_4bit,
    )
    FastLanguageModel.for_inference(model) # Enable native 2x faster inference

# alpaca_prompt = You MUST copy from above!

inputs = tokenizer(
[
    alpaca_prompt.format(
        "What is a famous tall tower in Paris?", # instruction
        "", # input
        "", # output - leave this blank for generation!
    )
], return_tensors = "pt").to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer)
_ = model.generate(**inputs, streamer = text_streamer, max_new_tokens = 128)